name: stable_conf
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults

dependencies:
  - python=3.12
  - numpy=1.26.4
  - rdkit=2023.09.6
  - pytorch=2.4
  - pytorch-cuda=11.8
  - pip
  - pip:
      - pymol2
